postgres-datavolume:
  image: busybox
  labels:
    io.rancher.container.start_once: true
    io.rancher.container.hostname_override: container_name
  entrypoint: /bin/true
  net: none
  volumes:
  - ${volume_path}:/var/lib/postgresql/data

postgres:
  image: postgres:9.5
  labels:
    io.rancher.sidekicks: postgres-datavolume
    io.rancher.container.hostname_override: container_name
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: #{affinity_label}
  environment:
    PGDATA: /var/lib/postgresql/data/pgdata
    POSTGRES_DB: ${dbname}
    POSTGRES_USER: ${dbuser}
    POSTGRES_PASSWORD: ${dbpassword}
  volumes_from:
  - postgres-datavolume
  tty: true
  stdin_open: true
