.catalog:
  name: "PostgreSQL"
  version: "9.5-4"
  description: "PostgreSQL server stack for simple one-node setup."
  uuid: postgres-9.5-0
  questions:
    - variable: "db_name"
      label: "Default Database Name"
      description: |
        This optional environment variable can be used to define a different name for the default database that is created when the image is first started.
        If it is not specified, then the value of <<dbuser>> will be used.
      type: "string"
      required: false
      default: "postgres"
    - variable: "db_user"
      label: "Superuser name"
      description: |
        Is used in conjunction with <<dbpassword>> to set a user and its password.
        This will create the specified user with superuser power and a database with the same name.
        If it is not specified, then the default user of postgres will be used.
      type: "string"
      required: false
      default: "postgres"
    - variable: "db_password"
      label: "Superuser password"
      type: "string"
      description: |
        Sets the superuser password for PostgreSQL. The default superuser is defined by the <<dbuser>> variable
      required: true
    - variable: "db_path"
      label: "Internal database data path"
      description: |
        This optional environment variable can be used to define another location - like a subdirectory - for the database files. The default is /var/lib/postgresql/data, but if the data volume you're using is a fs mountpoint (like with GCE persistent disks), Postgres initdb recommends a subdirectory (for example /var/lib/postgresql/data/pgdata ) be created to contain the data.
      type: "string"
      required: false
      default: "/var/lib/postgresql/data/pgdata"
    - variable: "volume_path"
      label: "Path on host for mount data volume"
      description: Fill path on host for mounting and saving data
      type: "string"
      required: true
    - variable: "affinity_label"
      label: "Affinity label"
      description: "Rancher Affinity label which using for scheduling"
      type: "string"
      required: true
      default: "postgres.enabled=true"
postgres:
  retain_ip: true
