.catalog:
  name: "PostgreSQL"
  version: "9.6.3-1"
  description: "PostgreSQL server stack for simple one-node setup."
  uuid: postgres-9.6.3-1
  questions:
    - variable: affinity_label
      label: Affinity label
      description: |
        Rancher host label which using for affinity in scheduling.
      type: string
      default: "postgres=enabled"
      required: true
    - variable: db_name
      label: Default Database Name
      description: |
        This optional environment variable can be used to define a different name for the default database that is created when the image is first started.
        If it is not specified, then the value of <<dbuser>> will be used.
      type: string
      required: false
      default: postgres
    - variable: db_user
      label: "Superuser name"
      description: |
        Is used in conjunction with <<dbpassword>> to set a user and its password.
        This will create the specified user with superuser power and a database with the same name.
        If it is not specified, then the default user of postgres will be used.
      type: string
      default: postgres
      required: false
    - variable: db_password
      label: Superuser password
      type: password
      description: |
        Sets the superuser password for PostgreSQL. The default superuser is defined by the <<dbuser>> variable
      required: true
    - variable: db_path
      label: Internal database data path
      description: |
        This optional environment variable can be used to define another location - like a subdirectory - for the database files. The default is /var/lib/postgresql/data, but if the data volume you're using is a fs mountpoint (like with GCE persistent disks), Postgres initdb recommends a subdirectory (for example /var/lib/postgresql/data/pgdata ) be created to contain the data.
      type: string
      required: false
      default: /var/lib/postgresql/data/pgdata
    - variable: volume_path
      label: Path on host for mount data volume
      description: Fill path on host for mounting and saving data
      type: string
      required: true
postgres:
  retain_ip: true
  scale: 1
  health_check:
    port: 5432
    interval: 2000
    unhealthy_threshold: 3
    healthy_threshold: 2
    response_timeout: 2000
