.catalog:
  name: Kong
  version: 0.10.3-0
  description: |
    The open-source API Gateway and Microservices Management Layer, delivering high performance and reliability.
  uuid: kong-0.10.3-0
  questions:
    - variable: AFFINITY_LABEL
      label: |
        Affinity label
      description: |
        Rancher host label which using for affinity in scheduling.
      type: string
      required: true
      default: "kong=enabled"
    - variable: KONG_DASHBOARD_HOSTNAME
      label: Kong Dashboard Hostname
      description: |
        Determines which hostname should be pointed to Kong Dashboard UI.
      type: string
      default: kong-dashboard
      required: true
    - variable: KONG_DASHBOARD_ADMIN_NAME
      label: Kond Dashboard Admin Name
      description: |
        Name is used for Basic Auth on Kong Dashboard
      type: string
      default: admin
      required: true
    - variable: KONG_DASHBOARD_ADMIN_PASSWORD
      label: Kond Dashboard Admin Password
      description: |
        Password is used for Basic Auth on Kong Dashboard
      type: password
      required: true
    - variable: KONG_DATABASE_SERVICE_LINK
      label: Link to Database Service
      description: |
        Rancher service which serve as Postgres or Cassandra server
      type: service
      required: true
    - variable: KONG_DATABASE
      label: Database Type
      description: |
        Determines which of PostgreSQL or Cassandra this node will use as its datastore.
      type: enum
      options:
        - postgres
        - cassandra
      default: postgres
    - variable: KONG_PG_PASSWORD_SECRET_KEY
      label: Postgres Password as Rancher Secret Key
      description: Name of Rancher secret key treated as Postgres database password
      type: string
      default: kong_pg_password
      required: true
    - variable: KONG_PG_USER
      label: Postgres User
      description: Postgres user.
      type: string
      default: kong
      required: true
    - variable: KONG_PG_DATABASE
      label: Postgres Database Name
      description: Database to connect to. Must exist.
      type: string
      default: kong
      required: true
    - variable: KONG_PG_PORT
      label: Postgres Port
      description: Port of the Postgres server.
      type: int
      default: 5432
      required: true
    # - variable: KONG_CLUSTER_ENCRYPT_KEY
    #   label: Cluster Encrypt Key
    #   description: Base64-encoded 16-bytes key to encrypt cluster traffic with.
    #   type: string
    - variable: KONG_CLUSTER_TTL_ON_FAILURE
      label: Cluster TTL On Failure
      description: |
        Time to live (in seconds) of a node in the cluster when it stops sending healthcheck pings, possibly caused by a node or network failure. If a node is not able to send a new healthcheck ping before the expiration, other nodes in the cluster will stop attempting to connect to it.

        Recommended to be at least 60.
      type: int
      default: 300
      required: true
    # - variable: pg_ssl
    # - variable: pg_ssl_verify
    - variable: KONG_LOG_LEVEL
      label: Log Level
      description: Log level of the Nginx server.
      type: enum
      options:
        - debug
        - info
        - notice
        - warn
        - error
        - crit
        - alert
        - emerg
      required: true
      default: notice
    - variable: KONG_ANONYMOUS_REPORTS
      label: Anonymous Reports
      description: Send anonymous usage data such as error stack traces to help improve Kong.
      type: enum
      options:
        - "on"
        - "off"
      default: "on"
    - variable: KONG_NGINX_WORKER_PROCESSES
      label: Nginx Worker Processes
      description: Determines the number of worker processes spawned by Nginx.
      type: string
      default: auto
      required: true
    - variable: KONG_MEM_CACHE_SIZE
      label: Memory Cache Size
      description: |
        Size of the in-memory cache for database entities. The accepted units are k and m, with a minimum recommended value of a few MBs.
      type: string
      default: 128m
      required: true
    - variable: KONG_UPSTREAM_KEEPALIVE
      label: Upstream Keepalive
      description: |
        Sets the maximum number of idle keepalive connections to upstream servers that are preserved in the cache of each worker process. When this number is exceeded, the least recently used connections are closed.
      type: int
      default: 60
      required: true
    - variable: KONG_SERVER_TOKENS
      label: Server Tokens
      description: |
        Enables or disables emitting Kong version on error pages and in the Server or Via (in case the request was proxied) response header field.
      type: enum
      options:
        - "on"
        - "off"
      default: "on"
    - variable: KONG_LATENCY_TOKENS
      label: Latency Tokens
      description: |
        Enables or disables emitting Kong latency information in the X-Kong-Proxy-Latency and X-Kong-Upstream-Latency response header fields.
      type: enum
      options:
        - "on"
        - "off"
      default: "on"

version: '2'
services:
  proxy:
    retain_ip: true
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 5000
      port: 8000
      unhealthy_threshold: 3
      initializing_timeout: 15000
      interval: 2000
      strategy: recreate
      reinitializing_timeout: 15000
  ui:
    scale: 2
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 5000
      port: 8080
      unhealthy_threshold: 3
      initializing_timeout: 5000
      interval: 30000
      strategy: recreate
      reinitializing_timeout: 5000
  lb-internal:
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - priority: 1
        protocol: http
        service: proxy
        source_port: 8000
        target_port: 8000
      - priority: 2
        protocol: http
        service: proxy
        source_port: 8001
        target_port: 8001
      - priority: 3
        protocol: http
        service: ui
        source_port: 8080
        target_port: 8080
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      strategy: recreate
      reinitializing_timeout: 60000
  lb-external:
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - priority: 2
        protocol: http
        service: lb-internal
        source_port: 80
        target_port: 8000
      - hostname: ${KONG_DASHBOARD_HOSTNAME}
        priority: 3
        protocol: http
        service: lb-internal
        source_port: 80
        target_port: 8080
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      strategy: recreate
      reinitializing_timeout: 60000
