name: Kong
description: |
  The open-source API Gateway and Microservices Management Layer, delivering high performance and reliability.
version: 0.10.3-1
category: Load Balancing, API Management, Microservices
